### ISSUE TITLE
为何要有英文？

### ISSUE THREAD

**Issue by upsuper** [bangumi/issues#1]
Bangumi好像没有英文受众吧，为何README里面需要有英文呢……？

**Comment by wattlebird** [comment]
This issue is not constructive.

**Comment by upsuper** [comment]
cc @fanzeyi

**Comment by BinotaLiu** [comment]
大概可以理解為 @fanzeyi 大大是先寫出英文再翻成中文的，
免責聲明那段中文甚至是我翻譯的wwww

**Comment by fanzeyi** [comment]
随便写着玩的 lol
