### ISSUE TITLE
当按年份浏览动画且在年份的第二页时，各个“年份”按钮无效且无悬浮月份菜单

### ISSUE THREAD

**Issue by fireattack** [bangumi/issues#10]
例子：http://bangumi.tv/anime/browser/airtime/2005

![qq 20151016145041](https://cloud.githubusercontent.com/assets/4130991/10551878/5c49e9b4-7415-11e5-9d60-f5c0c5ba2348.png)

与2011年对比：http://bangumi.tv/anime/browser/airtime/2011

![qq 20151016145000](https://cloud.githubusercontent.com/assets/4130991/10551874/52b6103a-7415-11e5-97ec-cb46ffa2ec62.png)

**Comment by Sai** [comment]
已修正
