### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by YDX-2147483647** [bangumi/issues#104]
刚注册而尚未验证邮箱时，会跳转到 https://bgm.tv/FollowTheRabbit。

> 呜咕，出错了
>
> 你的账户尚未激活，我们已向你的注册邮箱发送了一分包含激活码的邮件。
请根据邮件提示激活帐户。

![图片](https://github.com/user-attachments/assets/fa33d737-d3a7-4946-a740-48eb3fdd6b66)

这里把“一份”误写成了“一分”，希望改正。

**Comment by Sai** [comment]
Fixed
