### ISSUE TITLE
超展开无法在ipad设备中正常显示

### ISSUE THREAD

**Issue by markni** [bangumi/issues#105]
## 为什么不使用 /m?

大屏幕的ipad更适合使用桌面版的网页，能够使用完整的功能。

## 复现方法

用ipad打开超展开，可以看到列表没有高度设定，只能看到一小部分，无法正常使用。

没有ipad也可以在chrome里给user agent加入 "ipad"在电脑端复现。

![chrome_2024-10-05_15-12-09](https://github.com/user-attachments/assets/2149e417-95da-4a4e-9b3f-4fcf820cf827)

## 原因
https://bgm.tv/rakuen 有一段自适应高度的代码，刻意无视了ipad和iphone，造成两个`FrameWrapper`没有高度

```javascript
var resizeFrames = function() {
    if (navigator.userAgent.match(/iPhone/i)) {
    } else if (navigator.userAgent.match(/iPad/i)) {

    } else { 
        var height = getDocHeight();    
        document.getElementById('listFrameWrapper').style.height = (height - 60) + 'px';
        document.getElementById('contentFrameWrapper').style.height = (height - 60) + 'px';
    }
}



resizeFrames();

window.onresize = function() {
    resizeFrames();
}
```

**Comment by Sai** [comment]
用 Grid 重构了
