### ISSUE TITLE
自动域名转换bug

### ISSUE THREAD

**Issue by fireattack** [bangumi/issues#13]
http://bangumi.tv/group/topic/45272
http://bangumi.tv/group/topic/312448

 现在有许多人用 https://bgm.tv 的域名，如果用 bangumi.tv 访问的人看到就会被系统替换成 https://bangumi.tv 的链接，完全不work

**Comment by ershiwo** [comment]
其实是替换规则不用通配，强制bangumi和chii使用http访问就行（猜的

不过https是趋势，以后都加上证书才是最好的解决方法。

**Comment by BinotaLiu** [comment]
其實 bgm.tv 是 CloudFlare 的 SSL 吧，
，實際上 bangumi.tv:443 這個 Port 根本沒開

**Comment by aflyhorse** [comment]
```
[mask][url=https://bgm.tv/subject/698]测试[/url][/mask]
```
会被替换成
```
http://bgm.tv/group/topic/%5C%22https://bgm.tv/subject/698%5C%22
```
ref http://bgm.tv/group/topic/312642

赛老板之前一阵子开过HSTS，现在好像又关了

**Comment by BinotaLiu** [comment]
@aflyhorse 看起来跟本 Issue （自动域名转换）不相關，
已另開 Issue （=> #18）

**Comment by Sai** [comment]
Fixed, Timeline 吐槽部分的转换可能还有些问题
