### ISSUE TITLE
单行本以外的「关联条目排序」无效

### ISSUE THREAD

**Issue by BinotaLiu** [bangumi/issues#14]
[来源](https://bgm.tv/group/topic/312487)

> 如題。現狀是除了能在書籍部分給單行本排序、其他的話完全沒有起效。想必有一定編輯歷史的維基人也早就注意到這個bug(?)了，以前也肯定提出過希望能再改善排序功能吧…
碰到如下圖這種情況，以及那種出了很多衍生anthology漫畫的作品，真的很想順著円盤數字/出版順序來排序(強迫症(:q [___])

>![Image 1](http://r.loli.io/nmI3yy.png)
>![Image 2](http://r.loli.io/bqumQf.png)

**Comment by Sai** [comment]
Fixed
