### ISSUE TITLE
“按排名排序” 时 Pagination 的总条目数应不包含无 Rank 的条目

### ISSUE THREAD

**Issue by aflyhorse** [bangumi/issues#19]
在目前的时间点，“全部动画”“按排名排序”只有135页
https://bgm.tv/anime/browser?sort=rank&page=135
往后就没有内容了
然而下方导航栏提示有416页

**Comment by wattlebird** [comment]
The blank pages are reserved for unranked animations.

Currently, there are 9000+ animations in animation set. Only those which satisfy a condition will be listed in ranking list. The blank pages are reserved places for upcoming animations.

**Comment by aflyhorse** [comment]
IMHO they should be also appended without scores, or completely wiped out of the rank. Any normal button on a website should not redirect the browser to a blank screen.

**Comment by BinotaLiu** [comment]
不只是动画条目有这个问题，
参考下列两个链接就知道问题在哪里了：
https://bgm.tv/game/browser/airtime/2014-6
https://bgm.tv/game/browser/airtime/2014-6?sort=rank

以排名排序时，只会出现有 Rank 的条目，
但 Pagination 的总条目数似乎仍将无 Rank 的条目算进了

**Comment by Sai** [comment]
paging 都是有缓存的，筛选功能并不会重新计算对应的条目数量。
