### ISSUE TITLE
从收藏里删除条目，并不会更新对应列表页面navSubTabs里的数值

### ISSUE THREAD

**Issue by chaucerling** [bangumi/issues#25]
http://bangumi.tv/real/list/193869/do
这里就会出现有在看数目，但列表为空的情况
个人主页也是这种情况

**Comment by chaucerling** [comment]
好像是服务器页面缓存的问题

**Comment by BinotaLiu** [comment]
缓存非即时更新，先关闭，若确认有重大影响时再请打开本 Issue
