### ISSUE TITLE
被删除/被隐藏的日志继续关联在条目上，并显示摘要

### ISSUE THREAD

**Issue by aflyhorse** [bangumi/issues#26]
例，http://bgm.tv/subject/81281/reviews
这里的第四篇日志“2015summer”应当已被作者删除/隐藏，不再显示在[作者的日志列表](http://bgm.tv/user/yousei/blog)中，点击会跳转到bgm首页
我想从保护作者隐私的角度考虑，删除/隐藏的作品还是赶紧先匿掉比较好

**Comment by franklinyu** [comment]
補一個例子：[猎人随手记](https://bgm.tv/subject/1704/reviews)

**Comment by Sai** [comment]
Fixed
