### ISSUE TITLE
「我回复的话题」列表中栏位「最后回复时间」误植「发帖时间」

### ISSUE THREAD

**Issue by BinotaLIU** [bangumi/issues#27]
https://bgm.tv/group/my_reply
就是这个页面写「最后回复时间」，实际上底下的时间都是「发帖时间」

**Comment by franklinyu** [comment]
还有 https://bgm.tv/group/discover

**Comment by Sai** [comment]
Fixed

**Comment by fireattack** [comment]
http://bangumi.tv/group/my_reply 并没有fixed啊

**Comment by upsuper** [comment]
也许只是新版本还没部署……

**Comment by Sai** [comment]
刚部署，加了角色排序
