### ISSUE TITLE
人物频道中当有筛选条件时无法使用排序功能

### ISSUE THREAD

**Issue by BinotaLIU** [bangumi/issues#28]
若筛选条件是职业时，PASS：
https://bgm.tv/person?type=1&orderby=comment

血型，选择以评论数排序，应排序而未排序：
https://bgm.tv/person?bloodtype=1&orderby=comment

按性别、月份筛选时，选择以评论数排序也未排序
https://bgm.tv/person?gender=2&orderby=comment
https://bgm.tv/person?month=1&orderby=comment

**Comment by Sai** [comment]
Fixed
