### ISSUE TITLE
lain域名的链接替换会替出SITE_URL

### ISSUE THREAD

**Issue by aflyhorse** [bangumi/issues#32]
例，进入 http://lain.bgm.tv ，点击右上角自己的头像，会跳转到 http://lain.bgm.tv/SITE_URL/user/<ID>
这个域名虽然大家平时不会用，但百度和谷歌的时候给出的链接会指向它
我看lain主要是存图片（bangumi.tv和chii.in的图片也是指向lain.bgm.tv），要么给lain的VirtualHost加一个RedirectMatch？

**Comment by insulsa** [comment]
also affect navi.bgm.tv
https://bgm.tv/group/topic/341707

**Comment by insulsa** [comment]
related to [/issues/3 (fixed)](https://github.com/bangumi/issues/issues/3)

**Comment by insulsa** [comment]
不只右上角头象，还有右下角 body > div#dock 短信 设置 登出 显示春菜。但是导航栏 body > div > div > div > div > div > ul#navMenuNeue 下面的链接我看过想看搁置抛弃都正常。

**Comment by franklinyu** [comment]
还有 `ul#footerLinks`

**Comment by Sai** [comment]
lain & navi 不应该支持非静态资源访问，调整了 URL 规则，如有问题还请继续反馈。
