### ISSUE TITLE
编辑章节时若未填写标题会导致编辑丢失

### ISSUE THREAD

**Issue by BinotaLIU** [bangumi/issues#33]
Source: https://bgm.tv/group/topic/340125

未填写标题后会在送出后留在编辑页面（ `/ep/{EP_ID}/edit` ），
而 Bangumi 未正确将原本送出的资料回填至表单上，
导致编辑丢失。

这里可考虑为标题栏的 input 添加 required 属性（HTML5）。
添加后效果如下：
![HTML5 required attribute demo](http://puu.sh/ouhZO/813bc545a3.png)
submit 会被终止，并弹出提示。

**Comment by xuefer** [comment]
最好不要 required 全都可以省略算了

**Comment by Sai** [comment]
应该要允许省略
