### ISSUE TITLE
移动版时空管理局选择时间线类别时 AJAX 返回的翻页链接错误

### ISSUE THREAD

**Issue by protodonuts** [bangumi/issues#38]
例如:
进入 http://bgm.tv/m/timeline, 单击"吐槽"时, 会发送请求到
 http://bgm.tv/m/timeline?type=say&ajax=1

返回的数据中翻页 anchor 为
`<a href="http://bgm.tv/timeline?type=say&page=2" class="p">下一页 &rsaquo;&rsaquo;</a>`

这个超链接指向的本该是移动版的页面 bgm.tv<b>/m</b>/timeline?type=say&page=2

**Comment by Sai** [comment]
Fixed
