### ISSUE TITLE
404 页面的 HTTP Status Code 是 200

### ISSUE THREAD

**Issue by BinotaLIU** [bangumi/issues#4]

**Comment by Sai** [comment]
很多浏览器对 200 以外的 status code 不会返回网站的错误页，有什么解决方案？

**Comment by BinotaLiu** [comment]
鉴于我一发帖就被打脸说肯定是 Chrome 跟 Firefox 用的多，
所以目前可以不考虑其它浏览器吧，
现代浏览器应该都支持网站的自定义 404 页面了，
返回 200 对 SEO 也不好，
~~也不利于我做脚本~~

sai 说的**很多浏览器**例如什么呢？

**Comment by Hexcles** [comment]
@Sai AFAIK 只有 IE 在 status code 非200且返回的 HTML 长度过小 0.5 KiB 的时候才会显示所谓的“友好错误页面”。而 Chrome 好像会在返回全空的时候显示自己的错误提示。总而言之，只要不是 Apache/Nginx 的默认错误页面，一般情况下都够长、不会被浏览器 override 的才对。
