### ISSUE TITLE
captcha autocomplete

### ISSUE THREAD

**Issue by insulsa** [bangumi/issues#40]
symptom:
when filling the captcha, previously saved entries pop up as candidates. distract interaction, bad for screen real-estate.

affect:
2 pages with the login entry:
/
/login

with html
`<input id="captcha" name="captcha_challenge_field" class="inputtext" type="text">`

fix:
append html attribute
autocomplete="off"

also mentioned in:
https://bgm.tv/rakuen/topic/group/341648

**Comment by BinotaLIU** [comment]
> append
>  autocomplete="off"
>  in css

it's HTML attribute, not CSS

**Comment by Sai** [comment]
Fixed
