### ISSUE TITLE
lost of #fragment identifier when /rakuen/topic/ urls redirected

### ISSUE THREAD

**Issue by insulsa** [bangumi/issues#45]
在超展开中看讨论的时候儿，底下每一条儿小发言都带一个链接：
/rakuen/topic/(group|ep|prsn|crt)/[[:digit:]]+#post_[[:digit:]]+
如果点一下儿这个链接，页面会卷动（scroll）到这条发言，这条发言四周会出现蓝框。如果不点这个链接，而直接请求这个url，会重定向到相应讨论页的不带rakuen的形式，但#post_1234部分丢失了。

**Comment by Sai** [comment]
Fixed
