### ISSUE TITLE
(obsolete)

### ISSUE THREAD

**Issue by insulsa** [bangumi/issues#46]
Here used to be information I'm no longer willing to disclose. As i just now found out, not yet could delete an issue [github meta issue 253](https://github.com/isaacs/github/issues/253). I very hope @Sai take no action related to this matter. And I very hope friends talk about this matter in private channels.

**Comment by BinotaLIU** [comment]
It seems you don't want to discussing your question on GitHub.
Should I close this issue?

**Comment by Sai** [comment]
是有问题，已修正。

**Comment by franklinyu** [comment]
不想透露的話可以打馬賽克……

**Comment by touxing** [comment]
@insulsa 1
