### ISSUE TITLE
CDN 配置问题导致部分资源 fallback 到 http 连接

### ISSUE THREAD

**Issue by ershiwo** [bangumi/issues#47]
`https://lain.bgm.tv/pic/user/m/000/01/43/14382.jpg?r=1482912790` 如果直接访问此地址会强行跳到 http 地址 `http://bgm.tv/pic/user/m/000/01/43/14382.jpg?r=1482912790`，但是不加参数可以正确跳转到 https 地址。
怀疑是 CDN 缓存策略配置有问题。

**Comment by ershiwo** [comment]
bangumi 小组贴：http://bgm.tv/group/topic/341844

**Comment by Sai** [comment]
已修正
