### ISSUE TITLE
修改条目收藏与显示封面大图冲突

### ISSUE THREAD

**Issue by upsuper** [bangumi/issues#5]
重现步骤：
1. 点开任意自己收藏的条目
2. 点击右侧“收藏盒”内的修改
3. 保持修改框不关闭，点击左侧条目封面

预期结果：
收藏编辑框与条目封面互不干扰独立显示

实际结果：
封面大图显示在了收藏编辑框的下部，并且编辑框变窄

<img width="534" alt="屏幕截图" src="https://cloud.githubusercontent.com/assets/333750/10122032/4bdc01e8-654c-11e5-9e09-10bb330d8301.png">

**Comment by BinotaLiu** [comment]
thickbox 打开后 TB_overlay 应该要在后面把页面挡住才对
CSS 中 .TB_overlayActive 应改为 #TB_overlay
这样才符合[原版 Thickbox 的表现](http://codylindley.com/thickbox/)
Bangumi 这么做有其它考量吗？

**Comment by Sai** [comment]
Fixed
