### ISSUE TITLE
以时间筛选查看音乐，翻页后会丢失时间筛选

### ISSUE THREAD

**Issue by tyang34** [bangumi/issues#56]
在音乐部分，选择以时间筛选（如2015年），正常进入[页面](http://bgm.tv/music/browser/airtime/2015)，在该页无论以何种排序方式（rank或date或title）点选页数，都会丢失时间筛选信息。
以排名排序、2015年、页数3为例，原页面为[http://bgm.tv/music/browser/airtime/2015?sort=rank](http://bgm.tv/music/browser/airtime/2015?sort=rank)，进入的页面为[http://bgm.tv/music/browser?sort=rank&page=3](http://bgm.tv/music/browser?sort=rank&page=3)，而手动补全丢失的时间筛选信息能进入正确的页面（[http://bgm.tv/music/browser/airtime/2015?sort=rank&page=3](http://bgm.tv/music/browser/airtime/2015?sort=rank&page=3)）。

**Comment by fireattack** [comment]
在音乐部分，选择以时间筛选（如2015年），正常进入页面（http://bgm.tv/music/browser/airtime/2015 ），在该页无论以何种排序方式（rank或date或title）点选页数，都会丢失时间筛选信息。
以排名排序、2015年、页数3为例，原页面为 http://bgm.tv/music/browser/airtime/2015?sort=rank ，进入的页面为http://bgm.tv/music/browser?sort=rank&page=3 ，而手动补全丢失的时间筛选信息能进入正确的页面（http://bgm.tv/music/browser/airtime/2015?sort=rank&page=3 ）。

**Comment by Sai** [comment]
Fixed
