### ISSUE TITLE
An interesting bug for prohibited users

### ISSUE THREAD

**Issue by wattlebird** [bangumi/issues#58]
When visiting http://chii.in/user/128259, page writes:

> Chobits Said: MySQL Query Error
> 
> User: wattlebird
> Time: 2017-6-3 9:29pm
> Script: /router.php
> 
> SQL: SELECT * FROM [Table]blog_entry
> WHERE entry_uid = AND entry_public = 1 ORDER BY entry_dateline DESC LIMIT 0,4
> Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND entry_public = 1 ORDER BY entry_dateline DESC LIMIT 0,4' at line 2
> Errno.: 1064
> 
> Similar error report has beed dispatched to administrator before.

Similar situation appears for http://chii.in/user/sdf4 also.

**Comment by Sai** [comment]
Fixed
