### ISSUE TITLE
搜索优化

### ISSUE THREAD

**Issue by Sai** [bangumi/issues#6]
目前搜索用的是 CoreSeek http://www.coreseek.cn ，本质是 Sphinx + LibMMSeg。

分词都是默认配置，不知谁有时间可以看看如何调教以更好的支持中日文混合搜索？

**Comment by upsuper** [comment]
或许可以用MeCab来做日文分词之类？

**Comment by BinotaLiu** [comment]
目前有哪些字段建了索引？
记得除了标题之外内容简介好像也建了索引

**Comment by Sai** [comment]
标题，Infobox，描述都有索引，主要应该还是看 Sphinx 分词的配置。

**Comment by Sai** [comment]
看来是原来的分词引擎没有索引非中文英文之外的语言，目前用  N-gram 至少可以保证准确度。

**Comment by Sai** [comment]
目前应该基本可用，有什么需要修正的再开 Issue 吧。
