### ISSUE TITLE
代码长度超过留言框

### ISSUE THREAD

**Issue by Explorare** [bangumi/issues#62]
[終末なにしてますか? 综合楼（完结守墓、17.9.27 BD第四卷发售） (讨论:終末なにしてますか? 忙しいですか? 救ってもらっていいですか?)](https://bgm.tv/subject/topic/11040#post_94698)
这层的单行代码长度超过了留言框，应该自动添加个滑动条比较合适。

**Comment by benpigchu** [comment]
【 `overflow-x: auto;` 】

**Comment by Sai** [comment]
Fixed
