### ISSUE TITLE
以 HTTPS 访问天窗联盟时部分链接仍是 HTTP

### ISSUE THREAD

**Issue by ghost** [bangumi/issues#72]
1. 经由 HTTPS 访问天窗联盟主页 (https://doujin.bangumi.tv) 进行登录后会跳转至 HTTP。
   由于 Cookie 限制 Secure，跳转至 HTTP 后为未登录状态，需手动回到 HTTPS 页面。
2. 经由 HTTPS 访问时，登录后页顶用户名的下拉菜单中有关天窗联盟的几个链接都是 HTTP。

**Comment by BinotaLIU** [comment]
related to #68

**Comment by Trim21** [comment]
还有一些相关的问题:

```html
"background-image:url('//lain.bgm.tv/pic/crt/s/')"
```

在https的协议下会请求`https://lain.bgm.tv/pic/crt/s/`

然后会被301到`http://bgm.tv/pic/crt/s/` 导致某些请求变为HTTP请求
