### ISSUE TITLE
首页二级标题“游戏”的超链接指向错误

### ISSUE THREAD

**Issue by Onektas** [bangumi/issues#77]
指到“anime”去了。一年前就发现这个问题了，竟然到今天也没人提醒（第一次用GitHub的issues，应该能被正确看到吧）
<h2 class="title"><a href="/anime" class="l">游戏</a></h2>
应改为game
<h2 class="title"><a href="/《《game》》" class="l">游戏</a></h2>

**Comment by fireattack** [comment]
我这里没问题？具体点，是说最上面吗

**Comment by Onektas** [comment]
二级标题，h2标签里的。不知道图片能不能上传成功。具体位置，不是导航栏，是页面主体部分，蓝色大字。
![Uploading E91829A5-E4B4-477D-AA78-D02B8EA1B56C.png…]()

**Comment by fireattack** [comment]
哦，要没登录才能看到。而且是后面全错了，不光游戏。

你的图X了，帮你补个吧。

![image](https://user-images.githubusercontent.com/4130991/133637440-06f700dd-3a9e-49ab-86b3-5bf34338ffc1.png)

**Comment by Onektas** [comment]
图片传不了。以手机网页为例。最上方是导航栏，接下来是登入栏，然后下面是第一个二级标题，动画。再往下就是游戏

**Comment by Onektas** [comment]
回复效率有点高，总之能定位问题就ok，这个改一下应该很方便的
