### ISSUE TITLE
没有电波提醒历史记录

### ISSUE THREAD

**Issue by Explorare** [bangumi/issues#8]
[请问在哪里能看到电波提醒？ | Bangumi番組計画](https://bgm.tv/group/topic/312091#post_1075434)

**Comment by ershiwo** [comment]
这些不是bug，都是feature

**Comment by BinotaLiu** [comment]
@ershiwo
是功能請求，沒說是 Bug

**Comment by Explorare** [comment]
他说的是苹果梗「这不是bug，是feature」

**Comment by ershiwo** [comment]
所以推倒重做辣

**Comment by BinotaLiu** [comment]
我知道啊，但是毕竟没说是 Bug (bgm38)

推倒重做其实有点不太实际，毕竟站子不小，数据也不少

**Comment by ershiwo** [comment]
缝缝补补又三年

**Comment by BinotaLiu** [comment]
完全重做感觉是不可能吧，但是感觉可以慢慢把各模块换掉，
欢迎上 Slack 讨论 (bgm38)
https://bangumi-slack.herokuapp.com/

**Comment by Sai** [comment]
数据库都有保存，只是没显示出来。

**Comment by ershiwo** [comment]
应该做个页面查询一下了

**Comment by Explorare** [comment]
另外当多人在同一帖子回复时，点击提醒进去只会高亮最后一个回复，其他回复只能靠自己的智慧和记忆寻找了 (bgm38)

**Comment by upsuper** [comment]
@Explorare 你或许需要[讨论增强](https://github.com/bangumi/scripts/tree/master/upsuper#%E8%AE%A8%E8%AE%BA%E5%A2%9E%E5%BC%BA)这个脚本

**Comment by Explorare** [comment]
噫，好

**Comment by Explorare** [comment]
Chrome 上用什么脚本插件比较好呢？

**Comment by fireattack** [comment]
tampermonkey啊

**Comment by Sai** [comment]
/notify/all
