### ISSUE TITLE
public archive

### ISSUE THREAD

**Issue by Trim21** [bangumi/issues#80]
定期导出 wiki 数据方便一些不需要实时数据的场景，顺便希望减少一些爬虫。

导出的数据为主键和原始wiki内容，即用户在/subject/1/edit或类似页面填写的原始内容。

会导出的数据包括：

条目：
- 条目id 
- 条目名
- 条目中文名
- 原始wiki字符串
- 条目平台，即剧场版/tv/anime等等
- 条目简介
- nsfw

人物：
- 人物id
- 人物名
- 人物原始wiki字符串
- 人物简介
- 人物职业

角色同人物

条目之间的关联，条目，人物，角色两两之间的关联。

会导出为json lines格式，每个表单独一个文件。使用gzip压缩后放在github releases。

每周GMT+8 周三凌晨五点更新。

条目的原始SQL经过7z压缩后约100MB，整体应该不会很大。

@Sai

**Comment by Sai** [comment]
GMT+8 周三凌晨五点是访问低谷
