### ISSUE TITLE
创建条目时，输入漫画详情页链接，自动获取漫画名、封面、简介、作者等信息

### ISSUE THREAD

**Issue by lb-fes** [bangumi/issues#85]
减少复制粘贴，获取后，在手动修改提交
还有就是：上传封面能够直接输入图片链接上传，每次都要重复 图片另存→上传→删除

**Comment by trim21** [comment]
这两个是浏览器限制，无解…好像有类似的用户脚本/插件来着。

可以直接用鼠标把图片拖到本地文件夹里，再拖上传控件上。

**Comment by upsuper** [comment]
> 这两个是浏览器限制，无解…好像有类似的用户脚本/插件来着。

你从网页里当然不能直接抓别的地方的图片……但可以从服务器端代爬，当然那样又有别的问题就是了

**Comment by trim21** [comment]
用服务器爬有安全问题（
