### ISSUE TITLE
[Feature Request] 更改非维基人申请条目修改的形式

### ISSUE THREAD

**Issue by scientificworld** [bangumi/issues#92]
我大体设想的是，非维基人可以和维基人使用同一个编辑系统，但“提交修改”变为“提交修改请求”。维基人可以在专门页面上查看当前等待中的更改请求，并在确认无误（或进行修订）后将更改提交到条目。

目前的维基协力楼形式也没什么问题，不过个人认为这样改一下会更好一些。可以让有意向成为维基人的用户提前练习维基系统的使用，也能在一定程度上提高维基人工作效率。

**Comment by trim21** [comment]
这个我有过类似的想法，具体的等新的维基编辑功能上线之后再考虑。
