### ISSUE TITLE
部分页面无法打开

### ISSUE THREAD

**Issue by leohu1** [bangumi/issues#97]
eg:[魔女的夜宴](https://bgm.tv/subject/113290)
[星光咖啡馆与死神之蝶](https://bgm.tv/subject/289599)
猜测：都与柚子社有关？

**Comment by leohu1** [comment]
图片：
![图片](https://github.com/bangumi/issues/assets/47905372/5dbfd488-9747-4252-872b-d09128517486)

**Comment by trim21** [comment]
新注册的账号看不到18x条目

**Comment by leohu1** [comment]
好的？
