### ISSUE TITLE
维基人 - 条目编辑动态 - 条目 时间戳显示错误

### ISSUE THREAD

**Issue by fireattack** [bangumi/issues#99]
https://bgm.tv/wiki
![image](https://github.com/bangumi/issues/assets/4130991/2ca9c9a8-e660-4273-877f-89199d10a776)

应该显示最新编辑日期，实际显示的似乎是最早编辑日期

**Comment by fireattack** [comment]
锁定、合并也有类似问题。后面的似乎正常

**Comment by trim21** [comment]
应该已经修复了？

**Comment by fireattack** [comment]
看上去是的
